# Site settings
title: "Eduardo Corona"
email: jecorona97@gmail.com
description: "Personal Website"
baseurl: ""
url: ""
title_description: " this is a itle description"
title_image: "me.jpg"
google_analytics: "UA-111659041-1"
github_repository: ""
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _CoronaLight_
github_username:  jecorona97
instagram_username: jecorona97
reddit_username: 
linkedin_link: https://www.linkedin.com/in/coronaje/
google_plus_link: 
stackoverflow_link: 
xing_link:  
facebook_link: 

# Footer
footer_left: "2017 Eduardo Corona. Jekyll theme by Jacob Tomlinson"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
