# Site settings
title: "Eduardo Corona"
email: jecorona97@gmail.com
description: "Personal Website"
baseurl: ""
url: "https://jecorona97.github.io"
title_description: "I'm a Junior Computer Science student at the University of California, Irvine. Currently seeking opportunities that will challenge and further develop my problem solving, analytic and interpersonal skills."
title_image: "me.jpg"
google_analytics: "UA-111659041-1"
disqus_account:
github_repository: https://github.com/jecorona97/jecorona97.github.io
addthis_id: ""
post_limit: 5

# Social usernames/URLs
twitter_username: _CoronaLight_
github_username:  jecorona97
instagram_username: jecorona97
reddit_username: 
linkedin_link: https://www.linkedin.com/in/coronaje/
google_plus_link: 
stackoverflow_link: 
xing_link:  
facebook_link: 

# Footer
footer_left: "2017 Eduardo Corona. "
footer_right: "Jekyll theme by Jacob Tomlinson &lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
