# Site settings
title: "Jose Eduardo Corona Espinoza"
email: jecoronaespinoza@gmail.com
description: "Personal Website"
baseurl: ""
url: "https://jecorona97.github.io"
title_description: "I am a Computer Science student at UC Irvine currently seeking Software Engineering Full-ime opportunities. "
title_image: "me.jpg"
google_analytics: "UA-111659041-1"
disqus_account:
github_repository: https://github.com/jecorona97/jecorona97.github.io
addthis_id: ""
post_limit: 0

# Social usernames/URLs
twitter_username: edcorona_
github_username: jecorona97
instagram_username: jecorona97
reddit_username: 
linkedin_link: https://www.linkedin.com/in/coronaje/
google_plus_link: 
stackoverflow_link: 
xing_link:  
facebook_link: 

# Footer
footer_left: "2018 Eduardo Corona"
footer_right: "Jekyll"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
